---
- name: Check mysql is running
  service:
    name: mysql
    state: started
    enabled: yes

- name: Sets the root password
  mysql_user:
    login_unix_socket: /var/run/mysqld/mysqld.sock  # default path
    name: root
    password: "{{ mysql_root_password }}"
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: Removes the MySQL test database
  mysql_db:
    name: test
    state: absent
    login_user: root
    login_password: "{{ mysql_root_password }}"
